---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - image: aape2k/re-controller
          name: controller-image
          env:
#            todo: get values from config map + secret
            - name: JAR_FILES_PATH
              value: "/jars"
            - name: DB_EXTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: main-config-map
                  key: DB_EXTERNAL_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: main-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: main-config-map
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: main-config-map
                  key: DB_NAME
          volumeMounts:
            - mountPath: "/jars"
              name: jars-storage
          ports:
            - containerPort: 8080
      volumes:
        - name: jars-storage
          persistentVolumeClaim:
            claimName: local-pvc
---
