---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - image: aape2k/re-controller
          name: controller-image
          env:
#            todo: get values from config map + secret
            - name: JAR_FILES_PATH
              value: "/jars"
            - name: POSTGRES_EXTERNAL_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: "/jars"
              name: jars-storage
          ports:
            - containerPort: 80
      volumes:
        - name: jars-storage
          persistentVolumeClaim:
            claimName: local-pvc
---
