apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-manager
    namespace: default
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io
