apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-jars
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 300M
  hostPath:
    path: /data/persistent-volume