---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - image: aape2k/re-worker
        name: runner-image
        volumeMounts:
          - mountPath: /jarDir
            name: jar-volume
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
      volumes:
        - name: jar-volume
          emptyDir:
            sizeLimit: 100Mi
#        resources:
#          requests:
#            cpu: 10m
#            memory: 100Mi
#          limits:
#            cpu: 100m
#            memory: 100Mi
...